services:
  db:
    image: postgres:15-alpine                       # download lightweight PostgreSQL image
    container_name: pyfinance_db                    # set container name
    environment:                                    # set username, password, and database name
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=finance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data     # persist data (even if the container is removed)

volumes:
  postgres_data: